# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

margCompCompareC <- function(marg, comp) {
    .Call('imputeMulti_margCompCompareC', PACKAGE = 'imputeMulti', marg, comp)
}

sort_indexes <- function(values) {
    .Call('imputeMulti_sort_indexes', PACKAGE = 'imputeMulti', values)
}

supDistCpp <- function(x, y) {
    .Call('imputeMulti_supDistCpp', PACKAGE = 'imputeMulti', x, y)
}

